name: ckli
channels:
  - intel
  - defaults
dependencies:
  - python=3.6.8
  - scipy=1.2.1
  - ipython=7.7.0
  - matplotlib=3.0.3
  - jupyterlab=1.0.2
  - pyyaml=5.1.1
  - pip=10.0.1
  - pip:
    - gpy==1.9.8
    - paramz==0.9.5

